<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoviesTVShows.Model\MoviesTVShows.Model.csproj" />
    <ProjectReference Include="..\MoviesTVShows.Repository.Common\MoviesTVShows.Repository.Common.csproj" />
  </ItemGroup>

</Project>
